title: Cite's Blog
description: Blog
author: Cite Kanaumi
logo: images/cite.jpg
github: https://github.com/CiteKanaumi
about: 

baseurl: "/"
url: "https://citekanaumi.github.io"

allowsearch: true

disqus_shortname: Comment
google_analytics: UA-72862926-1

share:
  twitter_username: \#KU_cite
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]

